#
# TABLE STRUCTURE FOR: posts
#

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `community_id` int(10) unsigned DEFAULT NULL,
  `head` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `media_id` int(10) unsigned DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 1,
  `is_archived` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (1, 6, 13, 'Illum assumenda odio minus maxime accusantium.', 'Tempore perspiciatis dicta illo voluptatum dolores. Consequatur necessitatibus eveniet consectetur velit voluptate vel rem. Sed sint placeat ut molestiae veritatis.', 83, 0, 0, '2017-11-17 03:15:58', '2020-09-01 21:52:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (2, 48, 18, 'Ea aliquam rerum ex.', 'Ex exercitationem explicabo accusamus fugiat. Velit numquam eos maxime ipsam error inventore voluptas. In quam sed voluptates. Deleniti sit eveniet tempora magni id porro.', 8, 0, 0, '2020-01-09 20:01:55', '2020-09-02 04:59:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (3, 15, 20, 'Tenetur fugiat sed harum harum similique.', 'At quia consequuntur eos ut officia expedita. Ratione consequatur similique repellat dolor aut. Sint quia voluptatum accusantium consequuntur voluptatem autem.', 3, 1, 0, '2020-03-07 13:01:16', '2020-09-02 04:37:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (4, 21, 1, 'Exercitationem veritatis eos sed quo ipsum voluptatem.', 'Voluptates mollitia earum et. Expedita quia dolorem rerum dolorem saepe pariatur. Molestias natus natus beatae et maiores voluptatibus. Iste rem nobis dignissimos est.', 99, 0, 1, '2015-12-24 19:11:11', '2020-09-01 03:16:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (5, 13, 15, 'Deserunt rerum neque nesciunt ipsam aliquid optio eius.', 'Autem quae id animi corrupti quo ut. Amet ex enim debitis dolor sed assumenda eum cumque. Sed sed sit voluptas illo consequatur. Iste laboriosam laboriosam incidunt beatae voluptatibus.', 30, 1, 1, '2017-09-04 14:38:06', '2020-09-16 23:37:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (6, 93, 8, 'Eum sit ex nisi alias distinctio.', 'Eius doloribus sunt nihil ea. Id corrupti ea qui consequatur.', 94, 0, 0, '2019-12-07 07:37:44', '2020-08-21 09:07:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (7, 85, 10, 'Repellendus vel vero aut quo delectus exercitationem harum.', 'Dignissimos veniam sit dignissimos consectetur sed numquam et. Architecto molestiae cum debitis sint quibusdam dolorem. Excepturi qui iusto hic quis est sed alias.', 88, 1, 0, '2010-10-16 04:49:24', '2020-09-08 13:50:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (8, 86, 18, 'Minus molestiae molestiae atque nobis.', 'Animi debitis dolores excepturi omnis labore facere. Voluptatem nam sint officia ea. Non non nisi commodi ab.', 67, 1, 0, '2015-10-09 04:08:49', '2020-09-05 12:00:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (9, 53, 8, 'Aut soluta possimus quam repellat explicabo voluptates.', 'Est veniam odit doloremque aut. Quasi non et minima omnis quas non maxime. Amet et animi ea consectetur.', 19, 0, 0, '2015-07-24 17:27:23', '2020-09-07 22:40:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (10, 60, 10, 'Ullam assumenda ex accusantium maxime ullam.', 'Ullam voluptatem consequuntur voluptas perferendis officia. Et sint quia magni vel voluptate. Molestias nostrum quis nam officiis optio omnis. Deserunt et iure ipsam laboriosam a.', 13, 1, 1, '2015-12-02 19:02:54', '2020-09-04 05:24:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (11, 93, 14, 'Et magni non ut minus maxime ut voluptas autem.', 'Ex esse modi nobis delectus laboriosam omnis cum. Molestiae est atque et porro quia tempora. Quia et voluptatem dolor saepe ut consectetur fugiat.', 15, 1, 0, '2013-01-05 22:35:59', '2020-08-30 07:49:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (12, 13, 6, 'Soluta molestias et et dicta id.', 'Veniam et explicabo blanditiis aut in minima similique. Pariatur repellat sunt suscipit ipsam ducimus magnam. Inventore aspernatur consequuntur rerum qui.', 54, 0, 1, '2019-11-10 10:20:46', '2020-09-11 03:06:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (13, 41, 18, 'Ex doloremque eum rerum id corrupti numquam ut.', 'At enim et quas illum numquam. Enim voluptate tempora pariatur nostrum architecto similique. Provident iste incidunt itaque. Quia nihil doloremque ipsa exercitationem quisquam nisi rerum dolore. Delectus sed rerum ratione.', 15, 0, 1, '2020-03-12 20:31:23', '2020-08-23 23:58:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (14, 31, 20, 'Iusto qui iste voluptas voluptatem tenetur et.', 'Aut dolorum possimus ut numquam assumenda reiciendis. Autem aperiam consequatur labore et. Tenetur dolor voluptatum nostrum deserunt autem odio odit id.', 48, 1, 1, '2017-07-19 13:13:45', '2020-08-21 21:45:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (15, 36, 10, 'Iusto ipsam minima pariatur a magni sit.', 'Ut possimus minima labore et beatae in et ullam. Expedita ad reprehenderit sint illo sunt qui laborum. Rerum dolor eius voluptate velit aperiam fuga. Numquam sed non asperiores voluptate expedita.', 33, 0, 0, '2012-12-05 14:12:38', '2020-09-18 23:51:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (16, 56, 19, 'Est eaque alias et.', 'Sint fuga minus et qui ullam alias. Doloribus nostrum nihil impedit voluptates sunt occaecati et earum. Est rerum ex recusandae sunt. Repellendus deleniti eum voluptas tempora.', 17, 0, 1, '2011-03-24 08:33:36', '2020-09-10 11:14:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (17, 1, 14, 'Consequatur nemo iste dignissimos ad quia.', 'Qui qui voluptas totam dignissimos eos dolores. Voluptatem ipsam sequi recusandae eius rerum veniam. Hic voluptate in nihil aut quam. Ea laboriosam rerum et et quasi neque aliquid.', 56, 1, 1, '2019-07-11 15:22:09', '2020-09-06 05:08:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (18, 71, 9, 'Ab et molestias sint ab vel explicabo quaerat.', 'A et vero nulla doloremque enim sint. Enim enim dolorem rerum temporibus et modi odit. Architecto consequatur et distinctio dolorum totam aliquid sed.', 64, 0, 1, '2019-01-04 14:58:15', '2020-09-11 00:02:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (19, 57, 13, 'Et facilis deleniti possimus.', 'Placeat pariatur eligendi delectus quis voluptatem officia dolorem in. Labore qui autem error. Corporis nihil non quidem et dolores.', 55, 1, 1, '2020-03-16 02:36:33', '2020-09-08 18:36:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (20, 20, 18, 'Quam sit facere aut ipsa at et facere fugit.', 'Dolores impedit earum incidunt aspernatur doloremque et quas qui. At praesentium dolor reiciendis eos nemo soluta ut est. Maxime ut eum vel.', 9, 0, 1, '2012-01-06 00:00:55', '2020-08-30 18:25:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (21, 18, 11, 'Voluptates minima ea eum error vitae pariatur labore eaque.', 'Aliquam ipsam harum non reiciendis dignissimos qui. Quo sit incidunt cumque dicta. At ut qui nulla. Qui veniam dolorem autem veritatis.', 10, 1, 0, '2020-07-24 14:13:49', '2020-08-26 18:15:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (22, 71, 5, 'In fuga aut est.', 'Voluptatem eum non quisquam. Voluptatem repellendus expedita quae praesentium. Doloremque est in sequi.', 9, 1, 1, '2016-02-24 11:54:01', '2020-08-28 23:07:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (23, 74, 5, 'Architecto sed id tempora eum labore excepturi.', 'Recusandae ea eligendi perferendis tempore possimus. Fugit ea ut autem quam. Sunt et non molestias quo. Modi deleniti ipsum sit expedita consequuntur.', 28, 0, 0, '2017-02-04 19:20:02', '2020-08-30 14:56:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (24, 25, 12, 'Est voluptatem incidunt voluptatem officiis.', 'Qui est et facere vel fuga. Ipsum laborum quis molestiae architecto. A tenetur porro dolores itaque quod delectus quis deleniti.', 2, 0, 0, '2014-11-08 14:07:21', '2020-09-20 10:00:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (25, 1, 12, 'Quae voluptas totam ad facere maxime tempora.', 'Reiciendis provident qui enim ea nihil aut. Sint voluptas vitae est quia ex. Sunt et corporis iusto eos velit est sunt. Voluptatum id quae recusandae doloremque maxime aliquam omnis accusamus.', 60, 1, 1, '2014-11-05 10:22:26', '2020-08-30 13:48:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (26, 100, 10, 'Labore tempore perferendis quas sit atque.', 'Voluptate quo sed vitae. Consequuntur voluptates sunt quo nisi fuga.', 81, 1, 1, '2012-07-16 14:48:57', '2020-09-04 15:29:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (27, 99, 20, 'Ut fugiat adipisci libero aliquam.', 'Et nesciunt et ad qui velit culpa. Consequatur debitis possimus quis cum quidem quas expedita. Est inventore enim rem ipsum quasi enim quaerat. Dolores sunt eum aperiam autem suscipit.', 45, 0, 1, '2017-02-01 02:17:45', '2020-09-13 09:17:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (28, 4, 3, 'Incidunt voluptatem quia vitae deleniti quibusdam voluptatem eius.', 'Aut hic tempore cum totam eum deleniti beatae dolor. Ullam at ad odio et eius magni. Commodi incidunt doloribus aut maxime quaerat qui. Repellat animi ipsam et ullam.', 68, 1, 0, '2018-01-18 10:12:11', '2020-09-17 09:02:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (29, 55, 10, 'Debitis et rerum mollitia ea a vitae fuga incidunt.', 'Et amet labore totam culpa dolorum sed est. Voluptatibus doloribus nisi ipsum officiis et. Nihil aut eos a iure harum sit voluptas animi.', 68, 0, 0, '2016-11-10 00:51:41', '2020-09-19 20:06:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (30, 83, 8, 'Ut accusantium et nobis ut tempore voluptate.', 'Ea repellat incidunt nihil dolore. Quasi necessitatibus recusandae reprehenderit alias dolorum. Consequuntur rerum molestias provident aut itaque repellat. Sint aut et qui voluptatem aperiam corrupti veniam.', 75, 1, 1, '2015-09-17 21:55:33', '2020-09-10 07:58:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (31, 71, 12, 'Pariatur magnam voluptas veritatis dolores qui mollitia.', 'Rem quia a qui quia qui sunt. Consequatur dolor sed maiores dolores ratione.', 70, 1, 0, '2018-01-07 09:21:18', '2020-09-11 21:53:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (32, 17, 9, 'Ea quia in harum itaque provident.', 'Velit doloremque quidem totam ut quibusdam tenetur qui rem. Est illum maiores quaerat aperiam. Rerum sunt similique non ut adipisci corporis dolorem.', 79, 1, 0, '2019-10-04 12:12:28', '2020-08-22 14:05:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (33, 100, 20, 'Enim reiciendis consectetur alias molestias.', 'At molestiae ut doloribus fugiat et inventore. Suscipit ratione ut sint blanditiis id et assumenda illo. Dolorem explicabo sequi voluptas et aut labore sed.', 91, 0, 1, '2014-09-27 13:16:47', '2020-09-04 11:58:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (34, 40, 6, 'Quaerat et molestiae neque sit.', 'Quo est soluta porro eos aut. Est quia aut fugit nam accusamus odio. Aut consequatur atque sed. Quisquam accusamus temporibus est cupiditate recusandae similique accusamus.', 31, 0, 1, '2015-05-04 08:42:56', '2020-09-07 16:29:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (35, 53, 3, 'Et earum dignissimos nobis pariatur eum sed.', 'Pariatur numquam id earum sed cumque eaque nobis laudantium. Est corporis accusantium non iusto dignissimos totam ipsam et. Mollitia quis excepturi quo ab aut adipisci neque delectus.', 36, 0, 1, '2012-10-29 19:27:00', '2020-08-30 01:25:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (36, 61, 4, 'Excepturi odio tempora iste non provident quos.', 'Aspernatur consequatur asperiores eaque voluptas iste distinctio deserunt. Autem inventore eligendi soluta distinctio animi natus mollitia sit. Et accusamus labore reprehenderit et dignissimos aut.', 18, 1, 0, '2012-01-25 06:28:50', '2020-08-29 16:45:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (37, 35, 5, 'Quos necessitatibus rerum quia debitis et nisi est.', 'Velit illo exercitationem nostrum est. Debitis quo quisquam animi nihil fuga fugit qui exercitationem. Nisi sit omnis dolores. Voluptatem beatae accusamus id aliquam iste quo voluptatum iusto.', 40, 1, 1, '2014-07-17 03:43:46', '2020-09-06 12:07:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (38, 30, 10, 'Totam quia voluptatem ea qui explicabo.', 'Est temporibus non enim blanditiis repellat ut minima sit. Unde saepe exercitationem dolorem hic necessitatibus non dolores. Repellat aperiam natus et exercitationem aut ipsam qui aut.', 52, 1, 1, '2017-06-12 13:01:59', '2020-08-30 22:01:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (39, 15, 2, 'Voluptatem vero voluptas omnis.', 'Inventore quisquam et ut minima libero. Temporibus odio enim quisquam quia consectetur iure. Ullam corporis eum nulla beatae laudantium sapiente. Et a soluta quia.', 55, 1, 0, '2013-11-03 21:40:48', '2020-08-21 11:37:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (40, 70, 9, 'Aut enim soluta hic corrupti odit minus.', 'Aspernatur qui saepe eveniet et quo soluta aliquid. Id porro repellat iure voluptas consequatur beatae omnis laudantium. Iusto quidem commodi aut fugiat omnis accusantium aperiam.', 12, 1, 0, '2016-05-05 00:05:58', '2020-09-18 06:05:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (41, 2, 7, 'Animi quaerat molestiae ducimus voluptatum eius commodi doloribus.', 'Et numquam qui esse enim. Natus consequuntur nostrum sunt deserunt.', 65, 0, 1, '2012-08-03 20:56:13', '2020-09-11 06:39:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (42, 62, 16, 'Ut reiciendis eos quo quia maiores.', 'Quidem architecto sit omnis sit. Corporis labore molestiae voluptatibus quidem nesciunt. Odio vel est architecto rerum numquam perferendis. Ab sit totam iusto laudantium.', 44, 1, 0, '2014-09-25 00:11:55', '2020-09-17 17:30:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (43, 45, 14, 'Consequuntur minus temporibus sequi ut.', 'Magni expedita dolorum quia fugit molestias accusantium saepe. Reprehenderit illo earum et dolorem et hic. Aut sit cum aliquam id autem enim. Quia voluptas repudiandae quae. Animi porro magni sit sunt.', 92, 0, 0, '2018-04-15 12:30:34', '2020-09-19 15:27:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (44, 16, 8, 'Aut neque sunt sit velit sit deleniti recusandae.', 'Maiores sunt molestias beatae. Ex dolores iure qui voluptatem aliquid error est laboriosam. Tenetur quam aliquam culpa nihil. Enim et est et sed est.', 84, 0, 0, '2011-11-28 10:57:22', '2020-09-15 12:15:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (45, 47, 2, 'Quo quisquam quibusdam voluptatem ut sint et eos quisquam.', 'Aut earum quas maxime cupiditate quia corrupti quo. Voluptatem itaque ut odio minima sit. Facere veritatis numquam molestias.', 73, 0, 1, '2020-06-24 15:16:54', '2020-08-25 21:44:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (46, 91, 6, 'Aliquid rerum eaque quaerat voluptates architecto.', 'Velit et voluptates repellat modi occaecati tenetur quos incidunt. Placeat ex libero expedita neque ut ipsum fuga. Magnam reprehenderit sed dolorem.', 69, 0, 0, '2020-03-25 03:04:20', '2020-08-23 18:41:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (47, 3, 14, 'Recusandae natus ipsum eveniet rerum enim maiores assumenda.', 'Odio enim consequatur nobis aperiam. Quasi nemo inventore voluptas et quae. Veritatis omnis aut ut et nulla amet minima. Nulla officia quisquam saepe laudantium accusantium repellendus.', 64, 0, 1, '2020-04-29 13:04:38', '2020-09-04 16:36:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (48, 95, 8, 'Et delectus cupiditate debitis omnis sed inventore ut qui.', 'Non nihil similique eius alias. Et nostrum magni doloremque rerum totam. Vitae ducimus voluptatem quam consequatur repudiandae officiis temporibus debitis. Recusandae laboriosam blanditiis reprehenderit dolorem.', 10, 1, 0, '2016-02-08 09:50:40', '2020-09-11 15:21:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (49, 99, 3, 'Voluptate nesciunt animi ipsum rem harum commodi et.', 'Vero et voluptatem ullam aut nemo sint omnis. Distinctio et qui magnam voluptate odio omnis nihil. Nostrum et voluptatem ut non.', 30, 0, 1, '2020-04-21 16:56:45', '2020-09-08 21:43:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (50, 28, 11, 'Occaecati impedit deleniti officiis repellendus aut quis.', 'Unde non rerum suscipit quos reiciendis neque. Optio voluptate nihil molestiae molestiae blanditiis aliquam nisi. Quisquam id aperiam numquam molestias.', 43, 0, 1, '2016-09-20 02:40:50', '2020-09-05 07:04:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (51, 20, 9, 'Quia ea perspiciatis non aliquam voluptates.', 'Eaque in odio debitis illum vitae nulla sunt ad. Doloribus ea est adipisci consequuntur. Nobis laboriosam commodi tenetur ea.', 78, 1, 0, '2012-04-28 12:52:07', '2020-08-30 00:26:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (52, 26, 19, 'Beatae ipsam repellendus quo numquam ut laudantium et.', 'Autem non quasi quod accusantium et velit. Inventore tempora dolores qui. Ducimus vel soluta itaque neque vero aut doloremque.', 46, 0, 1, '2015-10-30 02:35:37', '2020-08-27 11:43:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (53, 11, 9, 'Cumque soluta dolores nobis maiores id iure.', 'Sint est quod et ratione. Deserunt nesciunt repellendus quasi distinctio nesciunt omnis similique sed. Pariatur qui cupiditate architecto voluptatem ipsa voluptatum.', 41, 0, 1, '2017-01-22 21:32:34', '2020-08-24 18:58:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (54, 39, 7, 'Reprehenderit nobis autem ut et.', 'Sit fuga nihil sint labore ab nihil at. Cupiditate sunt nisi eligendi voluptatem. Asperiores harum debitis non et voluptates consequuntur.', 12, 1, 0, '2017-10-28 03:45:06', '2020-08-28 07:55:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (55, 11, 15, 'Quos tempore vel numquam maxime.', 'Fugit aliquid iusto sed deleniti facilis. Aspernatur error recusandae cupiditate qui cum. Possimus rerum saepe voluptatem quasi voluptatibus nostrum. Officiis voluptatibus voluptatibus aut quod esse debitis dolor.', 89, 0, 0, '2011-08-12 18:15:10', '2020-09-09 14:39:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (56, 20, 8, 'Tempora eum repellendus deleniti voluptatem nihil qui.', 'Nobis voluptatem officiis tempora est eum vero. Quo similique et necessitatibus odio esse. Rem aut et autem quaerat veniam. Aut inventore sunt dolore optio.', 48, 0, 1, '2011-06-03 18:46:15', '2020-08-23 18:53:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (57, 90, 3, 'Aspernatur nulla non non.', 'Consequatur voluptas consectetur est doloremque consequatur. Qui dicta velit ullam adipisci sed. Fugit facilis inventore numquam qui velit.', 49, 0, 0, '2014-05-12 16:40:26', '2020-09-09 02:14:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (58, 35, 2, 'Repudiandae quo hic quia ratione.', 'Est fugit repellat numquam culpa laudantium voluptatibus harum. Deserunt pariatur est voluptatum dolor ut temporibus. Dolor ratione rerum ut rerum. Dolore cum laudantium neque soluta atque.', 20, 1, 0, '2010-11-07 04:42:42', '2020-08-31 07:11:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (59, 73, 5, 'Totam qui ut impedit sequi odio.', 'Consequatur expedita a et similique iste quas voluptas. Maxime reiciendis id aliquid facilis at ex autem. Quia dolore maiores laborum dolor et.', 5, 1, 0, '2012-10-09 03:04:57', '2020-09-05 13:45:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (60, 21, 4, 'Atque ut aliquam similique architecto totam natus ut reprehenderit.', 'Quaerat a eaque et non error eaque. Aspernatur voluptatum reprehenderit sed et ipsum earum. Enim quia ratione sit itaque est quis velit mollitia.', 42, 1, 1, '2012-12-08 07:37:41', '2020-08-21 22:46:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (61, 44, 9, 'Eos recusandae pariatur explicabo mollitia occaecati voluptas temporibus nam.', 'Nobis quo modi natus commodi numquam eius autem. Est maiores qui provident vel cumque hic. Sed eos nesciunt sed qui corporis.', 39, 0, 1, '2013-08-09 11:02:50', '2020-08-28 15:04:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (62, 47, 13, 'Numquam corrupti occaecati itaque sit eum quia.', 'Voluptas esse non ut dolor delectus tempora. Sed est ut et facilis. Eveniet hic sunt vero sequi. Libero ipsam ut quas sed nobis.', 36, 1, 1, '2015-09-23 00:45:56', '2020-09-07 21:10:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (63, 71, 19, 'Et animi doloribus mollitia.', 'Suscipit deserunt et qui in sint. Debitis ratione placeat et autem est in. Quos et dolores harum suscipit accusamus id.', 51, 0, 0, '2014-01-05 11:48:01', '2020-09-02 03:36:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (64, 20, 12, 'Aut non quia quia necessitatibus temporibus.', 'Esse dolor sed nam et iste rerum excepturi. Laborum sapiente perferendis accusantium non ex quos corrupti. Illo vero ut omnis consequatur.', 27, 1, 1, '2011-09-29 08:54:49', '2020-08-27 01:05:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (65, 5, 15, 'Esse fugiat rerum ut est corrupti.', 'Sit odio nemo odit voluptas itaque similique voluptatem ipsam. Architecto dolor qui molestias et qui. Quisquam possimus delectus facere omnis doloremque praesentium voluptates repellendus. Ab sit est ducimus repudiandae. Sint quaerat possimus necessitatibus laboriosam quam.', 4, 0, 0, '2014-10-07 01:05:26', '2020-09-02 16:42:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (66, 44, 14, 'Quia consectetur laborum tempore ut.', 'Ipsum non quia esse minima ratione iste. Accusamus earum officiis architecto dolores consequatur sequi asperiores. Debitis quisquam possimus odio nihil qui.', 13, 1, 0, '2011-03-20 00:52:32', '2020-08-23 11:57:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (67, 67, 18, 'Sed dolore aut est molestias qui impedit.', 'Voluptas nisi nihil et facere. Commodi facilis sunt sed est. Ullam perferendis ipsam molestiae fugit.', 91, 1, 1, '2018-09-02 01:38:58', '2020-09-08 11:27:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (68, 11, 10, 'Vitae consequatur est et.', 'Ipsum quis eveniet sit quasi aut. Ab ut sit ipsam omnis expedita in esse. Molestiae enim consectetur reprehenderit.', 14, 1, 0, '2010-10-27 16:31:46', '2020-09-09 21:27:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (69, 61, 18, 'Architecto veniam ratione alias ipsam quis dolor.', 'Consectetur repudiandae et fugiat nesciunt vitae ut. Et quaerat quas dignissimos eaque voluptatem a. Similique iusto et rerum minus. Officia iusto dicta rerum.', 57, 0, 1, '2015-10-04 05:16:57', '2020-09-08 04:17:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (70, 37, 8, 'Beatae quia ut reiciendis mollitia sit.', 'Consectetur non sed corrupti placeat id quo aliquid sint. Quo nam dicta eveniet. Consequatur molestiae illo libero voluptas provident. A suscipit ut quaerat porro.', 43, 1, 1, '2012-10-03 17:51:45', '2020-08-21 08:42:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (71, 97, 17, 'Nam accusamus iure laudantium sit maxime.', 'In vero quia ut et sequi voluptatibus. Deserunt et sunt quibusdam architecto est. Dolorum voluptate qui iste nam eius aperiam. Eligendi dignissimos possimus velit.', 17, 0, 1, '2019-05-08 05:08:42', '2020-09-12 13:17:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (72, 28, 10, 'Culpa unde qui ut aut.', 'At rerum illum autem qui quae et. Autem ea consequatur itaque distinctio. Odio officia provident deserunt commodi.', 47, 0, 0, '2018-12-29 01:18:15', '2020-08-21 15:04:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (73, 39, 10, 'Enim est consectetur praesentium quis nihil.', 'Rerum deleniti numquam hic beatae laudantium. Rem quia et occaecati. Quis provident et soluta. Inventore sit dolorem assumenda velit expedita corporis.', 37, 1, 0, '2012-11-15 12:50:44', '2020-09-15 03:20:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (74, 15, 17, 'Excepturi asperiores aut similique vero non est modi.', 'Tempora explicabo nemo quisquam repellendus. Et laborum quaerat asperiores ut. Et voluptas placeat culpa voluptas dolorem. Necessitatibus pariatur reprehenderit vel.', 31, 1, 0, '2015-12-13 01:41:33', '2020-09-18 13:35:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (75, 32, 13, 'Iste blanditiis aut nihil provident aspernatur eaque non est.', 'Et consequuntur architecto quos repellendus est voluptas est et. Ut numquam vel et aliquid aut aut. Quibusdam molestiae rerum consequuntur. Molestiae quisquam totam est assumenda vel.', 41, 0, 0, '2020-09-10 04:58:45', '2020-08-31 10:35:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (76, 5, 20, 'Eos laborum quis enim.', 'Quasi aut velit est ex. Ut et velit omnis esse ipsa soluta quidem. Debitis officia maiores quia a dicta. Ut commodi reiciendis unde velit iusto reprehenderit aspernatur.', 35, 1, 1, '2015-03-20 07:59:11', '2020-09-10 02:02:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (77, 87, 14, 'Optio at quasi neque iusto laboriosam.', 'Eum architecto aspernatur deleniti rerum dolorum. Harum nihil facilis temporibus. Nam laboriosam laudantium vel. Inventore voluptatem cumque molestiae quibusdam.', 59, 1, 0, '2015-10-16 03:15:24', '2020-09-10 10:31:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (78, 47, 2, 'Enim eaque laborum asperiores omnis beatae.', 'Modi nihil ut beatae itaque placeat. Eum sint iure rerum quisquam aperiam. Eum accusamus autem sint. Deserunt quasi eos adipisci harum dolorem labore excepturi.', 70, 0, 0, '2011-09-09 23:11:14', '2020-08-21 18:47:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (79, 16, 18, 'Aut mollitia illum soluta sit.', 'Rerum cumque repellendus est ipsam tempore exercitationem amet. Et quae quibusdam sed ut dolores dolore. Beatae laborum et necessitatibus cumque totam voluptatum eum. Ad sapiente vel accusantium.', 69, 1, 1, '2017-06-10 13:49:56', '2020-09-13 17:37:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (80, 17, 8, 'Odio quis omnis velit deleniti.', 'Reprehenderit dolorem dignissimos veniam ullam cumque. Amet quod natus cum error maiores nihil est. Earum quo ut numquam distinctio ut.', 44, 0, 0, '2012-01-12 20:50:50', '2020-08-28 04:30:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (81, 62, 3, 'Dolor officiis ea dolor animi quis.', 'Et quibusdam veniam nobis quas. Amet eos qui recusandae optio fugit doloremque illum amet. Error dolorem atque sit eligendi. Officiis modi debitis odio rem.', 17, 1, 0, '2016-04-14 07:35:52', '2020-09-16 16:52:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (82, 58, 19, 'Numquam occaecati eos magni officiis rerum.', 'Dolorem fugiat delectus quam et molestiae. Voluptas sed ipsum non. Omnis sit delectus ut dolore dolores blanditiis.', 20, 1, 0, '2016-11-03 08:26:41', '2020-08-27 14:28:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (83, 47, 3, 'Eveniet tempore libero expedita.', 'Voluptatem maiores ducimus officia incidunt cumque. Voluptas facere odit aut ratione et. Molestiae eos et ipsum eos nihil. Molestias aut impedit itaque voluptatem voluptatem dolorum. Enim quo sit sunt aperiam doloribus.', 29, 1, 0, '2012-10-08 16:02:54', '2020-08-25 06:08:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (84, 97, 18, 'Et rerum vero placeat maiores eius reiciendis non.', 'Eaque hic a rem aspernatur aut minima nulla. Nihil blanditiis vitae ea maiores qui nobis doloremque temporibus. Itaque animi tempore dolorum illum. Omnis laborum minima velit facilis vel repudiandae cumque.', 66, 0, 0, '2012-03-16 22:01:02', '2020-09-03 20:44:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (85, 15, 11, 'Doloribus optio incidunt quia ea.', 'Sint modi possimus debitis occaecati. Debitis est necessitatibus dignissimos et. Nihil in optio reprehenderit. Nobis earum qui voluptate iure repellendus sit.', 43, 0, 0, '2014-07-22 11:53:34', '2020-09-12 06:24:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (86, 96, 16, 'Maiores laborum dolorem ut libero et dolores.', 'Dolores ab dolore impedit beatae explicabo. Soluta incidunt quis accusantium qui nulla. Dolores dolorum error porro et.', 72, 0, 1, '2012-11-08 01:26:59', '2020-08-23 11:05:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (87, 50, 10, 'Doloremque voluptatum aut excepturi sit saepe praesentium.', 'Pariatur non nisi laudantium. Laudantium ipsa laboriosam vitae consequatur. Nisi beatae ad aspernatur.', 47, 1, 1, '2013-11-09 03:25:00', '2020-08-23 13:34:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (88, 60, 10, 'Maxime qui architecto et eum magnam.', 'Doloribus ducimus expedita eaque quidem reprehenderit molestiae. Voluptates cupiditate qui delectus qui unde quis. Sint mollitia laboriosam ab possimus dolorem voluptatum. Quo sunt voluptatum ut reprehenderit aut magnam libero.', 1, 1, 0, '2014-12-28 02:47:53', '2020-08-29 05:10:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (89, 13, 10, 'Eos aut exercitationem non temporibus sed ut hic cum.', 'Labore ducimus possimus doloribus ipsum molestias quod. Et laudantium iure sint nisi doloremque.', 98, 0, 0, '2017-12-30 19:42:36', '2020-08-24 13:14:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (90, 70, 15, 'Qui sint illum unde et nulla eos.', 'Velit doloremque eveniet sapiente soluta debitis veritatis. Velit ex omnis possimus ut suscipit rem itaque. Qui eum quibusdam voluptatem pariatur.', 82, 1, 1, '2018-06-07 23:32:24', '2020-09-19 05:30:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (91, 34, 5, 'Rerum et qui nihil laboriosam quisquam cumque quam.', 'Qui repellendus maiores perspiciatis qui quis impedit in. Nesciunt voluptatem quasi aut aliquid beatae ea. Esse est aspernatur eligendi et libero nostrum repellat. Et ipsum unde velit doloremque dignissimos eum laboriosam.', 5, 0, 1, '2020-09-02 02:23:14', '2020-08-31 22:48:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (92, 17, 20, 'Nemo quis omnis ex quo quo perspiciatis fuga accusantium.', 'Esse amet voluptatem est rerum. Et provident atque doloribus asperiores sed non. Quisquam autem aut culpa ipsum rerum.', 28, 0, 1, '2011-11-01 23:55:07', '2020-09-17 08:28:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (93, 59, 11, 'Voluptatem quisquam nesciunt aut rem.', 'Quam illum dolore consectetur qui qui quia doloremque. Quia doloribus hic enim explicabo est sequi sed. Delectus consequatur dolor autem sint repellendus.', 45, 0, 0, '2015-10-29 17:38:48', '2020-08-31 10:38:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (94, 100, 12, 'Ut distinctio nobis accusantium maiores facere.', 'Dolorum qui neque labore. Commodi sint iusto est voluptas quos. Debitis quo ipsa voluptatibus fuga laudantium.', 63, 0, 1, '2012-09-11 07:25:00', '2020-09-03 06:17:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (95, 68, 6, 'Totam exercitationem autem eius ut vero quaerat in.', 'A quibusdam doloribus eos consequatur qui. Omnis consequuntur aliquid enim cumque aspernatur. Architecto ad dolores iusto aspernatur soluta dolores omnis.', 47, 0, 0, '2014-12-18 19:47:58', '2020-09-16 18:48:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (96, 81, 13, 'Aut id similique ab eveniet sed.', 'Voluptate excepturi perspiciatis aspernatur velit non dolor necessitatibus. Voluptatem qui ad placeat consequuntur harum. Necessitatibus nostrum vitae eos molestiae eos modi. Expedita ut labore qui voluptas.', 5, 0, 1, '2011-03-11 03:22:42', '2020-09-15 02:04:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (97, 22, 20, 'Molestiae labore error ipsa beatae.', 'Et veritatis aut et ducimus in maiores quisquam. Quam impedit est eos voluptate ab. Aut optio accusantium odio necessitatibus.', 49, 1, 1, '2011-05-27 16:12:07', '2020-09-19 22:22:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (98, 27, 14, 'Sint atque qui labore sed.', 'Ipsum et quidem qui voluptas error officia. Blanditiis quos consectetur officiis sint eligendi animi. Alias omnis et alias asperiores repellendus. Iusto et maiores aliquam ipsa est dolore laboriosam culpa. Ab qui minus nostrum ea ea.', 6, 0, 0, '2017-04-22 03:05:08', '2020-09-12 06:10:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (99, 22, 14, 'Similique modi tenetur eum.', 'Error qui ipsam nisi vel maiores voluptatem deserunt. Vero magni quia nihil sed quis est. Ex nesciunt harum itaque omnis et ut at.', 89, 0, 0, '2013-05-27 17:39:11', '2020-09-01 19:18:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (100, 37, 10, 'Voluptas eos et dolor earum.', 'Dolorum omnis reprehenderit est autem voluptatum pariatur doloremque alias. Sed non id temporibus. Et suscipit porro quisquam. Unde rem voluptates et eaque laudantium qui.', 31, 1, 0, '2011-06-11 22:06:17', '2020-09-03 16:38:45');


